{% set name = "grand" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/essex-lab/grand/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c61ae8f2902f9332edf811f05f01858bfc386818ee531f6965eabe3453ccd30b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - pytest-runner
  run:
    - python >=3.8
    - openmmtools >=0.15.0
    - lxml
    - pymbar >=3.0.5
    - parmed
    - mdtraj
    - scipy
    - numpy

test:
  imports:
    - grand
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/essex-lab/grand
  summary: A Python module for carrying out GCMC insertions and deletions of water molecules in OpenMM.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
